/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ImageBucket-dev": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "TURSO_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_CONNECTION_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
